# Generated by Django 5.2.15 on 2026-06-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="products/"),
        ),
    ]
