# Generated by Django 5.2.15 on 2026-06-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_orderitem_discount_orderitem_gift_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="estimated_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="refunded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="return_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="serial_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="shipping_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="supplier_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tax_rate",
            field=models.DecimalField(decimal_places=2, default=0.22, max_digits=4),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="warehouse_location",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
